- environment: prod
  host: mydb.com
  ip: 189.175.1.1
  service: website
- environment: prod
  host: mydb.com
  ip: 189.175.1.2
  service: website
- environment: prod
  host: mydb.com
  ip: 189.175.1.3
  service: website
- environment: prod
  host: mydb.com
  ip: 189.175.1.4
  service: website
- environment: prod
  host: mydb.com
  ip: 189.175.1.5
  service: website
- environment: prod
  host: mydb.com
  ip: 189.175.1.6
  service: website
- environment: prod
  host: mydb.com
  ip: 189.175.1.7
  service: website
- environment: prod
  host: mydb.com
  ip: 189.175.1.8
  service: website
- environment: prod
  host: mydb.com
  ip: 189.175.1.9
  service: website
- environment: prod
  host: mydb.com
  ip: 189.175.1.10
  service: website
- environment: prod
  host: data.mydb.com
  ip: 189.175.2.1
  service: data services
- environment: prod
  host: data.mydb.com
  ip: 189.175.2.2
  service: data services
- environment: prod
  host: data.mydb.com
  ip: 189.175.2.3
  service: data services
- environment: prod
  host: data.mydb.com
  ip: 189.175.2.4
  service: data services
- environment: prod
  host: data.mydb.com
  ip: 189.175.2.5
  service: data services
- environment: prod
  host: data.mydb.com
  ip: 189.175.2.6
  service: data services
- environment: prod
  host: data.mydb.com
  ip: 189.175.2.7
  service: data services
- environment: prod
  host: data.mydb.com
  ip: 189.175.2.8
  service: data services
- environment: prod
  host: data.mydb.com
  ip: 189.175.2.9
  service: data services
- environment: prod
  host: data.mydb.com
  ip: 189.175.2.10
  service: data services
- environment: ppe
  host: ppe.mydb.com
  ip: 189.175.3.1
  service: website
- environment: ppe
  host: ppe.mydb.com
  ip: 189.175.3.2
  service: website
- environment: ppe
  host: ppe.mydb.com
  ip: 189.175.3.3
  service: website
- environment: ppe
  host: ppe.mydb.com
  ip: 189.175.3.4
  service: website
- environment: ppe
  host: ppe.mydb.com
  ip: 189.175.3.5
  service: website
- environment: ppe
  host: ppe.mydb.com
  ip: 189.175.3.6
  service: website
- environment: ppe
  host: ppe.mydb.com
  ip: 189.175.3.7
  service: website
- environment: ppe
  host: ppe.mydb.com
  ip: 189.175.3.8
  service: website
- environment: ppe
  host: ppe.mydb.com
  ip: 189.175.3.9
  service: website
- environment: ppe
  host: ppe.mydb.com
  ip: 189.175.3.10
  service: website
- environment: ppe
  host: ppe.data.mydb.com
  ip: 189.175.4.1
  service: data services
- environment: ppe
  host: ppe.data.mydb.com
  ip: 189.175.4.2
  service: data services
- environment: ppe
  host: ppe.data.mydb.com
  ip: 189.175.4.3
  service: data services
- environment: ppe
  host: ppe.data.mydb.com
  ip: 189.175.4.4
  service: data services
- environment: ppe
  host: ppe.data.mydb.com
  ip: 189.175.4.5
  service: data services
- environment: ppe
  host: ppe.data.mydb.com
  ip: 189.175.4.6
  service: data services
- environment: ppe
  host: ppe.data.mydb.com
  ip: 189.175.4.7
  service: data services
- environment: ppe
  host: ppe.data.mydb.com
  ip: 189.175.4.8
  service: data services
- environment: ppe
  host: ppe.data.mydb.com
  ip: 189.175.4.9
  service: data services
- environment: ppe
  host: ppe.data.mydb.com
  ip: 189.175.4.10
  service: data services
